import path from "node:path";
import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { writeFileSafe } from "../util/fs.js";
import { log } from "../util/log.js";
import type { DesignTokens } from "../capture/tokens.js";
import type { MobileManifest } from "./types.js";
import { REDESIGN_DIR, MOBILE_SUBDIR } from "../util/paths.js";

export interface MobileScaffoldOptions {
  out: string;
  artifacts: string;
}

const EMPTY_TOKENS: DesignTokens = {
  colors: [],
  backgrounds: [],
  fontFamilies: [],
  fontSizes: [],
  fontWeights: [],
  lineHeights: [],
  spacing: [],
  radii: [],
  shadows: [],
  roles: { accentCandidates: [] },
};

async function readJsonOr<T>(file: string, fallback: T): Promise<T> {
  try {
    if (!existsSync(file)) return fallback;
    return JSON.parse(await readFile(file, "utf8")) as T;
  } catch {
    return fallback;
  }
}

/** label "010_home_disponibles" → route slug "home_disponibles" (strips the milestone number). */
function slugFromLabel(label: string): string {
  const base = label.replace(/^\d+[_-]?/, "").replace(/[^a-zA-Z0-9_]+/g, "_").replace(/_+/g, "_");
  return base.replace(/^_|_$/g, "") || "screen";
}

function pascal(slug: string): string {
  const base = slug.replace(/[^a-zA-Z0-9]+/g, " ").trim() || "Screen";
  return base
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

/** Maps the pixel-derived tokens to a React Native theme object (no CSS on mobile). */
function tokensToRnTheme(tokens: DesignTokens): string {
  const r = tokens.roles;
  const background = r.dominantBackground ?? "#0b0b0c";
  const text = r.primaryText ?? "#e8e8ea";
  const surface = tokens.colors[1]?.value ?? background;
  const primary = r.accentCandidates[0] ?? "#3b82f6";
  const accent = r.accentCandidates[1] ?? primary;
  const palette = tokens.colors.slice(0, 8).map((c) => c.value);
  return `// Generated by redesigner from ../artifacts/tokens.json (palette extracted from
// screen PIXELS). Adjust the roles by hand — these are the most frequent colors, not
// necessarily the semantically correct ones.
export const theme = {
  colors: {
    background: ${JSON.stringify(background)},
    surface: ${JSON.stringify(surface)},
    text: ${JSON.stringify(text)},
    primary: ${JSON.stringify(primary)},
    accent: ${JSON.stringify(accent)},
    palette: ${JSON.stringify(palette)},
  },
  radius: { sm: 8, md: 12, lg: 18 },
  spacing: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32 },
} as const;

export type Theme = typeof theme;
`;
}

/**
 * Scaffolds a React Native / Expo (Expo Router) redesign project seeded with the mobile
 * tokens and one screen stub per captured screen. The Claude subagent then rebuilds the
 * screens following reports/redesign-brief.md; show/iterate runs the app on the device and
 * re-captures it with `mobile-capture`.
 */
export async function runMobileScaffold(opts: MobileScaffoldOptions): Promise<void> {
  const artifactsAbs = path.resolve(process.cwd(), opts.artifacts);
  const tokens = await readJsonOr<DesignTokens>(
    path.join(artifactsAbs, "tokens.json"),
    EMPTY_TOKENS,
  );
  const manifest = await readJsonOr<MobileManifest>(path.join(artifactsAbs, "manifest.json"), {
    source: "mobile",
    appId: "redesign",
    platform: "android",
    device: "",
    auth: "",
    startedAt: "",
    finishedAt: "",
    flows: [],
    screens: [],
    pages: [],
    warnings: [],
  });

  const root = path.resolve(process.cwd(), opts.out, REDESIGN_DIR, MOBILE_SUBDIR);
  const w = (rel: string, content: string) => writeFileSafe(path.join(root, rel), content);

  const appName = manifest.appId || "redesign";
  const screens = manifest.screens.slice(0, 16).map((s) => ({
    label: s.label,
    slug: slugFromLabel(s.label),
    comp: pascal(slugFromLabel(s.label)),
    screenshot: s.screenshot,
  }));
  // De-dup slugs (e.g. two "home"-ish screens) so routes don't collide.
  const seen = new Map<string, number>();
  for (const s of screens) {
    const n = seen.get(s.slug) ?? 0;
    seen.set(s.slug, n + 1);
    if (n > 0) {
      s.slug = `${s.slug}_${n + 1}`;
      s.comp = pascal(s.slug);
    }
  }
  const [home, ...rest] = screens;

  await w(
    "package.json",
    JSON.stringify(
      {
        name: "redesign-mobile",
        private: true,
        main: "expo-router/entry",
        scripts: {
          start: "expo start",
          android: "expo start --android",
          ios: "expo start --ios",
        },
        dependencies: {
          expo: "~52.0.0",
          "expo-router": "~4.0.0",
          "expo-status-bar": "~2.0.0",
          react: "18.3.1",
          "react-native": "0.76.5",
          "react-native-safe-area-context": "4.12.0",
          "react-native-screens": "~4.4.0",
        },
        devDependencies: {
          "@babel/core": "^7.25.0",
          "@types/react": "~18.3.0",
          typescript: "~5.3.0",
        },
      },
      null,
      2,
    ),
  );

  await w(
    "app.json",
    JSON.stringify(
      {
        expo: {
          name: "Redesign",
          slug: "redesign-mobile",
          scheme: "redesignmobile",
          orientation: "portrait",
          userInterfaceStyle: "automatic",
          newArchEnabled: true,
          plugins: ["expo-router"],
        },
      },
      null,
      2,
    ),
  );

  await w(
    "tsconfig.json",
    JSON.stringify(
      {
        extends: "expo/tsconfig.base",
        compilerOptions: { strict: true },
        include: ["**/*.ts", "**/*.tsx", ".expo/types/**/*.ts", "expo-env.d.ts"],
      },
      null,
      2,
    ),
  );

  await w(
    "babel.config.js",
    `module.exports = function (api) {
  api.cache(true);
  return { presets: ["babel-preset-expo"] };
};
`,
  );

  await w("theme.ts", tokensToRnTheme(tokens));

  await w(
    "app/_layout.tsx",
    `import { Stack } from "expo-router";
import { StatusBar } from "expo-status-bar";
import { theme } from "../theme";

export default function RootLayout() {
  return (
    <>
      <StatusBar style="light" />
      <Stack
        screenOptions={{
          headerStyle: { backgroundColor: theme.colors.surface },
          headerTintColor: theme.colors.text,
          contentStyle: { backgroundColor: theme.colors.background },
        }}
      />
    </>
  );
}
`,
  );

  const navLinks = rest
    .map((s) => `        <Link href="/${s.slug}" style={s.link}>${s.comp}</Link>`)
    .join("\n");

  await w(
    "app/index.tsx",
    `import { ScrollView, Text, View, StyleSheet } from "react-native";
import { Link } from "expo-router";
import { theme } from "../theme";
import { Button } from "../components/Button";
import { Card } from "../components/Card";

// Original screen: ${home?.label ?? "(none captured)"} — see ../../artifacts/screens/
export default function Home() {
  return (
    <ScrollView style={s.screen} contentContainerStyle={s.content}>
      <Text style={s.title}>Redesign</Text>
      <Text style={s.subtitle}>
        Base generada por redesigner. Reconstruí cada pantalla siguiendo
        reports/redesign-brief.md y las screenshots del survey.
      </Text>
      {/* TODO (Claude design): rebuild the home from its screenshot + the brief. */}
      <View style={s.row}>
        <Button title="Primary" />
        <Button title="Ghost" variant="ghost" />
      </View>
      <Card title="Card de ejemplo">Contenido con el tema sembrado desde tokens.json.</Card>
      <Text style={s.links_title}>Pantallas relevadas</Text>
      <View style={s.links}>
${navLinks || "        <Text style={s.subtitle}>(sin pantallas adicionales)</Text>"}
      </View>
    </ScrollView>
  );
}

const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.colors.background },
  content: { padding: theme.spacing.lg, gap: theme.spacing.md },
  title: { color: theme.colors.text, fontSize: 28, fontWeight: "700" },
  subtitle: { color: theme.colors.text, opacity: 0.7, fontSize: 15, lineHeight: 22 },
  row: { flexDirection: "row", gap: theme.spacing.sm, marginTop: theme.spacing.sm },
  links_title: { color: theme.colors.text, fontSize: 18, fontWeight: "600", marginTop: theme.spacing.lg },
  links: { gap: theme.spacing.sm },
  link: { color: theme.colors.primary, fontSize: 16, paddingVertical: 6 },
});
`,
  );

  for (const sc of rest) {
    await w(
      `app/${sc.slug}.tsx`,
      `import { ScrollView, Text, StyleSheet } from "react-native";
import { Stack } from "expo-router";
import { theme } from "../theme";

// Original screen: ${sc.label} — reference: ../../artifacts/${sc.screenshot}
export default function ${sc.comp}() {
  return (
    <ScrollView style={s.screen} contentContainerStyle={s.content}>
      <Stack.Screen options={{ title: "${sc.comp}" }} />
      {/* TODO (Claude design): rebuild this screen from its screenshot + the brief. */}
      <Text style={s.title}>${sc.comp}</Text>
    </ScrollView>
  );
}

const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.colors.background },
  content: { padding: theme.spacing.lg, gap: theme.spacing.md },
  title: { color: theme.colors.text, fontSize: 24, fontWeight: "600" },
});
`,
    );
  }

  await w(
    "components/Button.tsx",
    `import { Pressable, Text, StyleSheet } from "react-native";
import { theme } from "../theme";

export function Button({
  title,
  variant = "primary",
  onPress,
}: {
  title: string;
  variant?: "primary" | "ghost";
  onPress?: () => void;
}) {
  const ghost = variant === "ghost";
  return (
    <Pressable
      onPress={onPress}
      style={({ pressed }) => [
        s.base,
        ghost ? s.ghost : s.primary,
        pressed && { opacity: 0.85 },
      ]}
    >
      <Text style={[s.label, ghost && { color: theme.colors.text }]}>{title}</Text>
    </Pressable>
  );
}

const s = StyleSheet.create({
  base: { paddingHorizontal: 20, paddingVertical: 12, borderRadius: theme.radius.md, alignItems: "center" },
  primary: { backgroundColor: theme.colors.primary },
  ghost: { borderWidth: 1, borderColor: theme.colors.primary, backgroundColor: "transparent" },
  label: { color: "#fff", fontSize: 15, fontWeight: "600" },
});
`,
  );

  await w(
    "components/Card.tsx",
    `import { View, Text, StyleSheet } from "react-native";
import type { ReactNode } from "react";
import { theme } from "../theme";

export function Card({ title, children }: { title: string; children?: ReactNode }) {
  return (
    <View style={s.card}>
      <Text style={s.title}>{title}</Text>
      {children ? <Text style={s.body}>{children}</Text> : null}
    </View>
  );
}

const s = StyleSheet.create({
  card: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.lg, padding: theme.spacing.md, gap: 6 },
  title: { color: theme.colors.text, fontSize: 16, fontWeight: "600" },
  body: { color: theme.colors.text, opacity: 0.75, fontSize: 14 },
});
`,
  );

  await w("assets/README.md", "Drop the redesigned logo/icons here.\n");
  await w(".gitignore", "node_modules/\n.expo/\ndist/\n*.log\n");

  await w(
    "README.md",
    `# Redesign (mobile) — generated by redesigner

Base **React Native + Expo (Expo Router)** seeded with the surveyed app's tokens.

\`\`\`bash
npm install
npx expo install   # aligns native deps with the Expo SDK
npx expo start      # run on the device/emulator (Expo Go or a dev build)
\`\`\`

- Theme (from \`../artifacts/tokens.json\`) in \`theme.ts\`.
- One screen stub per surveyed screen under \`app/\` (Expo Router). \`app/index.tsx\` is the home.
- Base components in \`components/\`.

Rebuild each screen following \`../artifacts/reports/redesign-brief.md\` and the
matching screenshot in \`../artifacts/screens/\`.

**Show / iterate:** run the app on the device, then re-capture it with the skill's
\`mobile-capture\` (point \`--app\` at this app's id) to screenshot the redesign and compare it
against the original survey screens.
`,
  );

  log.success(`Mobile redesign scaffold at: ${root} (${screens.length} screen stub(s))`);
  log.info("Next (Claude design): rebuild the screens guided by reports/redesign-brief.md.");
}
