/**
 * Generates the "split mode" as a SUBVIEW of the redesign itself (not as a
 * separate artifact). The `CompareShell` wraps the app: by DEFAULT it shows the
 * SPLIT (a curtain with a draggable handle that also follows the mouse) of the
 * ORIGINAL site (captured offline in `public/_original/`) over the real redesign.
 *
 * - "Before" side: iframe to `/_original/html/<slug>.html` (offline, local assets).
 * - "After" side: the real redesign (direct render, `children`).
 * - Synchronized scroll ONLY in split (the original is same-origin).
 * - Switching pages (dropdown) ALSO navigates the redesign via `route`, and
 *   navigating the redesign updates the dropdown.
 * - The curtain follows the mouse by default; a button (or a click on the ⇔ handle)
 *   PINS it so you can hover/click on the redesign.
 */

export interface OriginalPageInfo {
  slug: string;
  title: string;
  url: string;
}

/** Tentative redesign route (hash) for an original slug. Adjustable. */
function guessRoute(slug: string): string {
  if (!slug || slug === "home" || slug === "index") return "#/";
  return "#/" + slug;
}

/** Data module `src/lib/original.ts` with the list of original pages. */
export function originalDataSource(pages: OriginalPageInfo[]): string {
  const items = pages.map((p) => ({
    slug: p.slug,
    title: p.title || p.slug,
    url: p.url,
    src: `/_original/html/${p.slug}.html`,
    route: guessRoute(p.slug),
  }));
  return `// Generated by redesigner: captured ORIGINAL site pages ("before" side of
// the CompareShell). They are served offline from public/_original/.
//
// \`route\` = the equivalent REDESIGN route (hash), to sync the view on both
// sides. It is a per-slug guess: ADJUST IT to your redesign's real routes
// (e.g. event_detail -> "#/event/35").
export interface OriginalPage {
  slug: string;
  title: string;
  url: string;
  src: string;
  route: string;
}

export const ORIGINAL_PAGES: OriginalPage[] = ${JSON.stringify(items, null, 2)};
`;
}

/** Component `src/CompareShell.tsx`. */
export function compareShellSource(): string {
  return `import { useEffect, useRef, useState, type ReactNode } from "react";
import { ORIGINAL_PAGES } from "./lib/original";

type Mode = "before" | "split" | "after";
const ACCENT = "#6d4aff";

// First segment of a hash ("#/event/35" -> "event"; "#/" -> "").
function seg(hash: string): string {
  return hash.replace("#/", "").replace("#", "").split("/")[0];
}

/**
 * BEFORE/AFTER comparison shell that wraps the app.
 * Default: SPLIT — a curtain that follows the mouse, original (offline iframe) over
 * the real redesign (children). The [Before][Split][After] buttons pin each side.
 * - Synchronized scroll ONLY in split (in Before/After each side scrolls on its own).
 * - Switching pages (dropdown) ALSO navigates the redesign (route), and navigating
 *   the redesign updates the dropdown.
 * - "Follow the mouse" is ON by default; the 🖱️ button or a click on the ⇔ handle
 *   PINS it (and then the handle is draggable), freeing hover/click.
 * - Double click: only the new design fullscreen; another double click goes back.
 */
export function CompareShell({ children }: { children: ReactNode }) {
  const hasOriginals = ORIGINAL_PAGES.length > 0;
  const [mode, setMode] = useState<Mode>("split");
  // immersive (fullscreen) for one side: "before" = original, "after" = redesign.
  const [immersive, setImmersive] = useState<null | "before" | "after">(null);
  const [x, setX] = useState(50);
  const [idx, setIdx] = useState(0);
  const [follow, setFollow] = useState(true); // the curtain follows the mouse (default)
  const [barOpen, setBarOpen] = useState(true); // floating menu visible
  const stage = useRef<HTMLDivElement>(null);
  const beforeRef = useRef<HTMLIFrameElement>(null);
  const dragging = useRef(false);
  const moved = useRef(false);

  const current = ORIGINAL_PAGES[idx];
  const reveal =
    immersive === "before" ? 100 : immersive === "after" ? 0 : mode === "before" ? 100 : mode === "after" ? 0 : x;
  const showCompare = hasOriginals && !immersive;

  // Page selection: changes the original (iframe) AND navigates the redesign.
  function selectPage(i: number) {
    setIdx(i);
    const route = ORIGINAL_PAGES[i]?.route || "#/";
    if (window.location.hash !== route) window.location.hash = route;
  }

  // Navigating the redesign (children) updates the original's dropdown.
  useEffect(() => {
    const onHash = () => {
      const s = seg(window.location.hash);
      const i = ORIGINAL_PAGES.findIndex((p) => seg(p.route) === s);
      if (i >= 0) setIdx((cur) => (cur === i ? cur : i));
    };
    window.addEventListener("hashchange", onHash);
    return () => window.removeEventListener("hashchange", onHash);
  }, []);

  // Synchronized scroll ONLY in split.
  useEffect(() => {
    if (!showCompare || mode !== "split") return;
    const onScroll = () => {
      const w = beforeRef.current?.contentWindow;
      if (!w) return;
      try {
        w.scrollTo(0, window.scrollY);
      } catch {
        /* noop */
      }
    };
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, [showCompare, mode, idx]);

  // Handle drag (to fine-tune when it is pinned).
  useEffect(() => {
    function onPM(e: PointerEvent) {
      if (!dragging.current || !stage.current) return;
      moved.current = true;
      const r = stage.current.getBoundingClientRect();
      setX(Math.max(0, Math.min(100, ((e.clientX - r.left) / r.width) * 100)));
    }
    function onPU() {
      dragging.current = false;
    }
    window.addEventListener("pointermove", onPM);
    window.addEventListener("pointerup", onPU);
    return () => {
      window.removeEventListener("pointermove", onPM);
      window.removeEventListener("pointerup", onPU);
    };
  }, []);
  function startDrag(e: React.PointerEvent) {
    dragging.current = true;
    moved.current = false;
    e.preventDefault();
  }
  // Click on the handle (without dragging) = toggle pinned/follow mouse.
  function toggleFollow() {
    if (moved.current) {
      moved.current = false;
      return;
    }
    setFollow((f) => !f);
  }
  // "Follow the mouse" (default): the curtain tracks the cursor in split.
  function onMove(e: React.MouseEvent) {
    if (!showCompare || mode !== "split" || !follow || dragging.current || !stage.current) return;
    const r = stage.current.getBoundingClientRect();
    setX(Math.max(0, Math.min(100, ((e.clientX - r.left) / r.width) * 100)));
  }
  // Double click = fullscreen of the clicked SIDE (left=original / right=redesign).
  // Another double click returns to split and the menu ALWAYS reappears.
  function enterOrExit(side: "before" | "after") {
    if (!hasOriginals) return;
    setImmersive((cur) => {
      const next = cur ? null : side;
      if (!next) {
        setMode("split");
        setBarOpen(true);
      }
      return next;
    });
  }
  function onDbl(e: React.MouseEvent) {
    const r = stage.current?.getBoundingClientRect();
    let side: "before" | "after" = "after";
    if (r) {
      const curtain = r.left + (r.width * reveal) / 100;
      side = e.clientX < curtain ? "before" : "after";
    }
    enterOrExit(side);
  }

  return (
    <div
      ref={stage}
      onMouseMove={onMove}
      onDoubleClick={onDbl}
      style={{ position: "relative", minHeight: "100vh" }}
    >
      {/* AFTER — the real redesign (base layer). */}
      {children}

      {/* BEFORE — offline original, clipped from the left.
          ALWAYS mounted (not unmounted in immersive mode) so it is NOT re-downloaded
          when returning to split (avoids the white flash). Only hidden via display.
          High z-index to cover fixed/sticky elements of the redesign (navbar). */}
      {hasOriginals && current && (
        <iframe
          key={current.src}
          ref={beforeRef}
          src={current.src}
          title={"Before — " + current.title}
          onLoad={() => {
            try {
              if (mode === "split") {
                beforeRef.current?.contentWindow?.scrollTo(0, window.scrollY);
              }
              // double click INSIDE the original (left side) → original to
              // fullscreen; otherwise the iframe swallows the event.
              const doc = beforeRef.current?.contentDocument;
              doc?.addEventListener("dblclick", () => enterOrExit("before"));
            } catch {
              /* same-origin expected; if it fails, nothing breaks */
            }
          }}
          style={{
            position: "fixed",
            inset: 0,
            width: "100%",
            height: "100%",
            border: 0,
            background: "#fff",
            zIndex: 9000,
            display: immersive === "after" ? "none" : "block",
            pointerEvents:
              immersive === "before" || (!immersive && mode === "before") ? "auto" : "none",
            clipPath: "inset(0 " + (100 - reveal) + "% 0 0)",
          }}
        />
      )}

      {/* Divider + handle (only in split). */}
      {showCompare && mode === "split" && (
        <div
          style={{
            position: "fixed",
            top: 0,
            bottom: 0,
            left: reveal + "%",
            width: 2,
            background: ACCENT,
            transform: "translateX(-1px)",
            zIndex: 9001,
            pointerEvents: "none",
          }}
        >
          <div
            onPointerDown={startDrag}
            onClick={toggleFollow}
            title={follow ? "Click = pin · drag = move" : "Click = follow the mouse again · drag = move"}
            style={{
              position: "absolute",
              top: "50%",
              left: "50%",
              transform: "translate(-50%, -50%)",
              width: 40,
              height: 40,
              borderRadius: 99,
              background: follow ? ACCENT : "#fff",
              color: follow ? "#fff" : ACCENT,
              display: "grid",
              placeItems: "center",
              fontWeight: 800,
              boxShadow: "0 4px 14px #0008",
              pointerEvents: "auto",
              cursor: follow ? "pointer" : "ew-resize",
              touchAction: "none",
              border: "2px solid " + ACCENT,
            }}
          >
            {follow ? "⇔" : "🔒"}
          </div>
        </div>
      )}

      {/* Control bar (hidden in immersive mode or if closed with the X). */}
      {showCompare && barOpen && (
        <div
          style={{
            position: "fixed",
            top: 12,
            left: "50%",
            transform: "translateX(-50%)",
            zIndex: 9002,
            display: "flex",
            gap: 10,
            alignItems: "center",
            padding: "7px 10px",
            borderRadius: 12,
            background: "#151517ee",
            border: "1px solid #34343a",
            color: "#e8e8ea",
            font: "13px/1.2 system-ui, sans-serif",
            backdropFilter: "blur(8px)",
          }}
        >
          <select
            value={idx}
            onChange={(e) => selectPage(Number(e.target.value))}
            style={{
              background: "#1b1d20",
              color: "#e8e8ea",
              border: "1px solid #34343a",
              borderRadius: 8,
              padding: "5px 8px",
              maxWidth: 220,
              font: "inherit",
            }}
          >
            {ORIGINAL_PAGES.map((p, i) => (
              <option key={p.slug + i} value={i}>
                {p.title}
              </option>
            ))}
          </select>
          <div style={{ display: "inline-flex", gap: 3, background: "#1b1d20", border: "1px solid #34343a", borderRadius: 9, padding: 3 }}>
            {(["before", "split", "after"] as Mode[]).map((m) => (
              <button
                key={m}
                type="button"
                onClick={() => setMode(m)}
                style={{
                  border: 0,
                  borderRadius: 7,
                  padding: "5px 11px",
                  font: "inherit",
                  fontWeight: 600,
                  cursor: "pointer",
                  background: mode === m ? ACCENT : "transparent",
                  color: mode === m ? "#fff" : "#b8b8c0",
                }}
              >
                {m === "before" ? "Before" : m === "split" ? "Split" : "After"}
              </button>
            ))}
          </div>
          <button
            type="button"
            onClick={() => setFollow((f) => !f)}
            title={follow ? "The split follows the mouse — click to pin" : "Split pinned — click to make it follow the mouse"}
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: 6,
              borderRadius: 8,
              padding: "6px 11px",
              font: "inherit",
              fontWeight: 600,
              cursor: "pointer",
              border: "1px solid " + (follow ? ACCENT : "#34343a"),
              background: follow ? ACCENT : "#1b1d20",
              color: follow ? "#fff" : "#b8b8c0",
            }}
          >
            <span aria-hidden style={{ fontSize: 14 }}>🖱️</span>
            {follow ? "Follow mouse" : "Pinned"}
          </button>
          <span style={{ opacity: 0.55, fontSize: 12 }}>
            {follow ? "double click = only the new design" : "drag ⇔ · double click = only the new one"}
          </span>
          <button
            type="button"
            onClick={() => setBarOpen(false)}
            title="Close menu (double click on the canvas shows it again)"
            style={{
              border: 0,
              background: "transparent",
              color: "#b8b8c0",
              cursor: "pointer",
              font: "inherit",
              fontWeight: 800,
              fontSize: 15,
              lineHeight: 1,
              padding: "2px 4px",
            }}
          >
            ✕
          </button>
        </div>
      )}

      {/* Chip to reopen the menu if it was closed with the X. */}
      {showCompare && !barOpen && (
        <button
          type="button"
          onClick={() => setBarOpen(true)}
          title="Show comparison menu"
          style={{
            position: "fixed",
            top: 12,
            left: "50%",
            transform: "translateX(-50%)",
            zIndex: 9002,
            display: "inline-flex",
            alignItems: "center",
            gap: 6,
            padding: "6px 12px",
            borderRadius: 999,
            border: "1px solid #34343a",
            background: "#151517cc",
            color: "#e8e8ea",
            font: "13px/1 system-ui, sans-serif",
            fontWeight: 600,
            cursor: "pointer",
            backdropFilter: "blur(8px)",
          }}
        >
          ⇔ menu
        </button>
      )}
    </div>
  );
}
`;
}
