import path from "node:path";
import { writeFileSafe, writeJson } from "../util/fs.js";
import { log } from "../util/log.js";
import { tokensToThemeCss } from "./theme.js";
import { tokensToFigma } from "./figma-tokens.js";
import type { DesignTokens } from "../capture/tokens.js";
import { REDESIGN_DIR, HTML_SUBDIR } from "../util/paths.js";

export interface HtmlExportOptions {
  out: string;
  artifacts: string;
  tokens: DesignTokens;
}

/**
 * "HTML mock" export: a single static HTML file with Tailwind v4 (browser CDN) and
 * the tokens in a <style>@theme. It serves as a simple mock and as a base for
 * importing into Figma with the html.to.design plugin. It also emits tokens.figma.json.
 */
export async function exportHtmlMock(opts: HtmlExportOptions): Promise<void> {
  const root = path.resolve(process.cwd(), opts.out, REDESIGN_DIR, HTML_SUBDIR);
  const theme = tokensToThemeCss(opts.tokens);

  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Redesign — mock</title>
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  <style type="text/tailwindcss">
${theme}
  </style>
</head>
<body class="bg-surface text-text font-sans">
  <header class="sticky top-0 border-b border-black/10 backdrop-blur">
    <nav class="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
      <span class="text-lg font-bold">Brand</span>
      <div class="flex gap-6 text-sm">
        <a href="#" class="opacity-80 hover:opacity-100">Home</a>
        <a href="#" class="opacity-80 hover:opacity-100">Products</a>
        <a href="#" class="opacity-80 hover:opacity-100">Contact</a>
      </div>
    </nav>
  </header>
  <main class="mx-auto max-w-5xl px-6 py-16">
    <h1 class="text-4xl font-bold tracking-tight">Redesign</h1>
    <p class="mt-4 text-lg opacity-80">Static mock generated by redesigner. Edit by hand or import into Figma with html.to.design.</p>
    <div class="mt-8 flex gap-4">
      <button class="rounded-lg bg-primary px-5 py-2.5 text-sm font-medium text-surface hover:opacity-90">Primary</button>
      <button class="rounded-lg border border-black/20 px-5 py-2.5 text-sm font-medium hover:bg-black/5">Secondary</button>
    </div>
    <div class="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
      ${[1, 2, 3]
        .map(
          (i) => `<div class="rounded-xl border border-black/10 p-6 shadow-md">
        <h3 class="text-lg font-semibold">Card ${i}</h3>
        <p class="mt-2 text-sm opacity-75">Sample content.</p>
      </div>`,
        )
        .join("\n      ")}
    </div>
  </main>
</body>
</html>
`;

  await writeFileSafe(path.join(root, "index.html"), html);
  await writeJson(path.join(root, "tokens.figma.json"), tokensToFigma(opts.tokens));
  log.success(`HTML mock at: ${root}`);
  log.info("Open index.html in the browser, or import it into Figma with the html.to.design plugin.");
  log.info("tokens.figma.json can be imported with the Tokens Studio plugin.");
}
