import type { DesignTokens } from "../capture/tokens.js";

/** Normalizes a color value into something usable as a CSS var. */
function clean(v: string): string {
  return v.trim();
}

/**
 * Maps the captured design tokens to a Tailwind v4 `@theme` block (CSS-first).
 * Generates semantic names + the raw palette as a reference.
 */
export function tokensToThemeCss(tokens: DesignTokens): string {
  const lines: string[] = [];
  lines.push("/* Generated by redesigner from the original site's tokens.json.");
  lines.push("   Adjust the roles by hand: these are the MOST FREQUENT values,");
  lines.push("   not necessarily the semantically correct ones. */");
  lines.push("@theme {");

  // Inferred semantic roles.
  const r = tokens.roles;
  if (r.primaryText) lines.push(`  --color-text: ${clean(r.primaryText)};`);
  if (r.dominantBackground && !/rgba\(0, 0, 0, 0\)/.test(r.dominantBackground))
    lines.push(`  --color-surface: ${clean(r.dominantBackground)};`);
  if (r.accentCandidates[0]) lines.push(`  --color-primary: ${clean(r.accentCandidates[0])};`);
  if (r.accentCandidates[1]) lines.push(`  --color-accent: ${clean(r.accentCandidates[1])};`);

  // Raw palette as a reference (palette-1..n).
  tokens.colors.slice(0, 8).forEach((c, i) => {
    lines.push(`  --color-palette-${i + 1}: ${clean(c.value)}; /* x${c.count} */`);
  });

  // Typography.
  if (tokens.fontFamilies[0])
    lines.push(`  --font-sans: ${clean(tokens.fontFamilies[0].value)};`);
  if (tokens.fontFamilies[1])
    lines.push(`  --font-display: ${clean(tokens.fontFamilies[1].value)};`);

  // Typographic scale (sorted font sizes).
  const sizes = tokens.fontSizes
    .map((s) => parseFloat(s.value))
    .filter((n) => !Number.isNaN(n))
    .sort((a, b) => a - b);
  const scaleNames = ["xs", "sm", "base", "lg", "xl", "2xl", "3xl", "4xl"];
  sizes.slice(0, scaleNames.length).forEach((px, i) => {
    lines.push(`  --text-${scaleNames[i]}: ${px}px;`);
  });

  // Radii.
  tokens.radii.slice(0, 4).forEach((rad, i) => {
    const name = ["sm", "md", "lg", "xl"][i];
    lines.push(`  --radius-${name}: ${clean(rad.value)};`);
  });

  // Shadows.
  tokens.shadows.slice(0, 3).forEach((sh, i) => {
    const name = ["sm", "md", "lg"][i];
    lines.push(`  --shadow-${name}: ${clean(sh.value)};`);
  });

  lines.push("}");
  return lines.join("\n") + "\n";
}
